../rtl/rvsingle_top.v
../rtl/riscv_single.v
../rtl/imem.v
../rtl/dmem.v
../rtl/controller.v
../rtl/datapath.v
../rtl/alu.v
../rtl/adder.v
../rtl/mux2.v
../rtl/mux8.v
../rtl/pc_reg.v
../rtl/extend.v
../rtl/reg_file.v
../rtl/mux4.v
../pattern/tb_rvsingle.v
../pattern/tb_alu.v
../pattern/tb_mem.v
../pattern/tb_extend.v
../pattern/tb_regfile.v
